#+BEGIN_HTML
---
layout: page
title: "Alfred Tips"
date: 2013-06-05 22:20
comments: true
sharing: true
footer: true
---
#+END_HTML

Alfred is awesome! Check it out at: [[http://www.alfredapp.com/][www.alfredapp.com]]. I really never use the
=Applications= folder or other mechanisms to find applications on my Mac. The
basic features are free! However, the small price for the "Powerpak" is totally
worth it.

Here's the some of the ways that I use Alfred. If you've got suggestions that I
should add, please add a comment below.

* Bring up Alfred 
I'm using "Double Tap Cmd Key" to bring up Alfred, and then I type any
application I want to visit, type =space= and then a file or folder name.

* Powerpack Features
I use these 2 Powerpack features all the time:

** Copy Buffer
Cmd-Opt-C brings up a list of all recent copy actions on my Mac.

** Workflows
+ [[https://github.com/BubiDevs/manage-hidden-files][Manage hidden files]], by Andrea Busi. Toggle the finder's showing of hidden
  files. (keyword =hiddden=) 
+ [[http://cloud.dferg.us/2A7l][Switch Audio Input and Output]]: Useful to switch from my external hi-fi to my
  screen speakers so that when I teleconference, there is no echoing. (keyword
  =input= and =output=)
+ [[https://github.com/ctwise/alfred-workflows][Time Machine]], By Ted Wise: Allows you to start and stop Time Machine from
  Alfred. Ted has many other Alfred workflows at this git repository. (keyword:
  =tmac start= and =tmac stop=)
