#+BEGIN_HTML
---
layout: post
title: "Contributing to Discourse.org via CodeClimate"
date: 2013-08-24 09:38
comments: true
categories: [discourse, emberjs]
keywords: 
description: How to contribute to Discourse (Discourse.org) via suggestions from CodeClimate.
published: false
---
#+END_HTML


This article gives a quick background into:
1. Why contribute to Discourse?
2. How to use CodeClimate to contribute?

This is the first part in a series of articles. The following articles will
provide examples of improving the discourse.org codebase.


* Why Discourse?
The two hottest areas of modern web development are arguably Ruby on Rails and
EmberJs. Supposing you've gone through tutorials, but what if you want to see a
serious production application? Discourse
(https://github.com/discourse/discourse) provides just such an example. In May,
I covered this topic in great detail: [[http://www.railsonmaui.com/blog/2013/05/25/getting-started-with-discourse/][Getting Started With Discourse]].

* Get Involved
Supposing you want to contribute to Discourse, what's an easy place to get
started? For starters, check out this thread at Discourse.org: [[http://meta.discourse.org/t/so-you-want-to-help-out-with-discourse/3823][So, you want to
help out with Discourse]]. The cool thing is that you're using Discourse to learn
how to contribute to it!

