#+BEGIN_HTML
---
layout: post
title: "CoffeeScript Chrome Extensions"
date: 2013-05-27 17:16
comments: true
categories: coffeescript
keywords: coffeescript
description: Useful tools for Chrome with CoffeeScript 
published: true
---
#+END_HTML

Here's 3 useful tools for using [[http://coffeescript.org/][CoffeeScript]] for web development, possibly with
Rails and EmberJs. All 3 tools are useful for different purposes. 

* CoffeeScript Source Maps: Debugging CoffeeScript Directly
With Source Maps, you don't have to mentally convert your CoffeeScript code into
JavaScript code in the debugger. Instead, you can now see your CoffeeScript
code, even with correct line numbers. This rails gem, [[https://github.com/markbates/coffee-rails-source-maps][coffee-rails-source-maps]],
makes it easy to include CoffeeScript source maps as part of your rails
application. Note, the =Rails.env.development?= is hard coded, so this only works
when you use that specific environment. You can also do it manually, by using
the =-m= flag with the =coffee= command.
{% img /images/2013-05-27-coffeescript-chrome-extensions/coffeescript-source-map.png %}

#+begin_html
<!-- more -->
#+end_html

* Try CoffeeScript Chrome Extension: Converting between CoffeeScript and JavaScript
The [[https://chrome.google.com/webstore/detail/try-coffeescript-enhanced/fldhkfldchaibgaheaogapecjmnkaepe?hl%3Den][Try CoffeeScript Enhanced]] Chrome extension is pretty nice for converting
between JavaScript and CoffeeScript. The main advantage over
http://js2coffee.org is that the you don't have to open a new browser tab, and
you can enter either CoffeeScript or JavaScript.

{% img /images/2013-05-27-coffeescript-chrome-extensions/try-coffeescript.png %}

* Coffee Console Developer Tool: Executing CoffeeScript in Chrome
"[[http://snook.ca/archives/browsers/coffeeconsole][Coffeeconsole: A Chrome Extension]]" provides a place to execute CoffeeScript in
the Web Inspector.
{% img /images/2013-05-27-coffeescript-chrome-extensions/coffee-console.png %}



