#+BEGIN_HTML
---
layout: post
title: Golden Gate Ruby Conference (GoGaRuCo) Pictures 2014
date: 2014-09-28 20:47:46 -1000
comments: true
categories: 
keywords: 
description: 
---
#+END_HTML


I took lots of great pictures at the [[http://gogaruco.com/][2014 Golden Gate Ruby Conference]] this year.

Overall, the conference was awesome. All the speakers seemed incredibly well
prepared.

In case you haven't heard, this was the last GoGaRuCo conference. Why? I heard
that the costs for the facility are going up, especially the costs for catering.
I also suspect that other new conferences, such as [[http://emberconf.com/][Ember Conf]], are competing for
attention. And certainly it's been a huge undertaking for the conference
organizers.

I've been toying around with creating a Rails on Maui Conference, and I've just
created a [[%20http://forum.railsonmaui.com/t/about-the-maui-conference-category/71][forum for just this sort of discussion]].

#+begin_quote
Should we have a Maui Rails Conference? Let's discuss the possibility of such a
conference here. I'd need at least several committed co-organizers in order for
this to become a reality. A possible date would be next September, 2015, given
that GoGaRuCo will no longer take place.

I'd propose having a smaller, less formal conference for the first year. I've
got a very reasonably priced venue in mind that could take up to 100
participants.

Ideas? Want to help?
#+end_quote

I've broken the pictures up into smaller sets of the best pictures which I've
placed in Facebook albums. Then I've got the complete sets of images posted to
Flickr.

If you need any full resolution, non-watermarked images, please get in touch
with me.

* Facebook Images
About the better 1/3 of shots I took.
1. [[https://www.facebook.com/media/set/?set%3Da.872787302733036.1073741849.484394724905631&type%3D3&uploaded%3D13][Day 0, Pre-Party]]
2. [[https://www.facebook.com/media/set/edit/a.872789892732777.1073741850.484394724905631/][Day 1, Conference]]
3. [[https://www.facebook.com/media/set/?set%3Da.872785476066552.1073741848.484394724905631&type%3D3][Day 1, After-Party at Hired]]
4. [[https://www.facebook.com/media/set/?set%3Da.872776112734155.1073741844.484394724905631&type%3D3&uploaded%3D111][Day 2, Conference]]
5. [[https://www.facebook.com/media/set/?set%3Da.872777182734048.1073741845.484394724905631&type%3D3][Day 2, After Party]]

* Flickr All Images
1. [[https://www.flickr.com/photos/justingordon/sets/72157648169297102/][Day 0, Pre-Party]]
2. [[https://www.flickr.com/photos/justingordon/sets/72157648123422496/][Day 1, Conference]]
3. [[https://www.flickr.com/photos/justingordon/sets/72157647773600368/][Day 1, After-Party at Hired]]
4. [[https://www.flickr.com/photos/justingordon/sets/72157648177152432/][Day 2, Conference]]
5. [[https://www.flickr.com/photos/justingordon/sets/72157648194362625/][Day 2, After Party]]

#+begin_html
<!-- more -->
#+end_html

* Favorite Shots
{% img /images/2014-09-28-gogaruco-pictures-2014/gogaruco-1.jpg %}

{% img /images/2014-09-28-gogaruco-pictures-2014/gogaruco-2.jpg %}

{% img /images/2014-09-28-gogaruco-pictures-2014/gogaruco-3.jpg %}

{% img /images/2014-09-28-gogaruco-pictures-2014/gogaruco-4.jpg %}

{% img /images/2014-09-28-gogaruco-pictures-2014/gogaruco-5.jpg %}

{% img /images/2014-09-28-gogaruco-pictures-2014/gogaruco-6.jpg %}

{% img /images/2014-09-28-gogaruco-pictures-2014/gogaruco-7.jpg %}

{% img /images/2014-09-28-gogaruco-pictures-2014/gogaruco-8.jpg %}

{% img /images/2014-09-28-gogaruco-pictures-2014/gogaruco-9.jpg %}

{% img /images/2014-09-28-gogaruco-pictures-2014/gogaruco-10.jpg %}

{% img /images/2014-09-28-gogaruco-pictures-2014/gogaruco-11.jpg %}

{% img /images/2014-09-28-gogaruco-pictures-2014/gogaruco-12.jpg %}

{% img /images/2014-09-28-gogaruco-pictures-2014/gogaruco-13.jpg %}
