#+BEGIN_HTML
---
layout: post
title: "2014 Golden Gate Ruby Conference: Top 10 Reasons to Attend"
date: 2014-08-13 14:25:57 -1000
comments: true
categories: [rails, conferences] 
keywords: Rails, GoGaRuCo, Golden Gate Ruby Conference, Conference
description: My top reasons to attend the 2014 Golden Gate Ruby Conference (GoGaRuCo).
canonical: https://www.shakacode.com/blog/2014-golden-gate-ruby-conference/
#+END_HTML

Woo hoo! I'm going to the [[http://gogaruco.com/][2014 Golden Gate Ruby Conference]]. It's at UCSF Mission
Bay, San Francisco, September 19-20, 2014. I wrote an article about my
experience last year, [[http://www.railsonmaui.com/blog/2013/09/22/gogaruco-2013/][GoGaRuCo 2013: Community > Code]]. If you're on the fence
about attending, here's my top reasons on why you should consider attending. I
recommend not delaying [[http://gogaruco.com/registration/][signing up]], as last year I saw folks begging for tickets
once the conference sold out. According to [[https://twitter.com/wifelette][Leah Silber]], one of the [[http://gogaruco.com/about/][conference
organizers]], GoGaRuCo has sold out every year, except for /maybe/ year one.

* Top 10 Reasons To Attend GoGaRuCo

1. San Francisco is a great town to visit, and there's no better month to visit
   than September as dense fog is least likely!
2. It's relatively small conference, compared to Rails Conf, and I find that
   *much more engaging and relaxing*. The attendees seem to be a mix of highly
   passionate Rubyists, mostly locals, with a mix from around the world.
3. A one track conference is nice in that you don't have to worry about picking
   which talks to attend.
4. There's a 15 minute break between each talk to socialize with fellow
   attendees or speakers. Socializing is why you come to these talks!
5. Yehuda will likely come up with some interesting talk!
6. Ruby programming is really more of an art and passion than work, and the
   people that attend GoGaRuCo reflect this!
7. You'll probably make a few new friends and leave inspired.
8. The food is super, both at the conference and throughout the city. And the
   evening events last year were great as well.
9. There's probably going to be a job board, just in case that interests you.
10. You won't need any more T-shirts for another year!

#+begin_html
<!-- more -->
#+end_html

* Photography
I'm volunteering as the official photographer of GoGaRuCo. My mission is to "get
2-3 good shots of each speaker, a couple of audience shots during each days
lunch and breaks, a shot or two of each exhibitor table, 2-3 team photos, and a
smattering of everything else." So please don't be shy and ask to have your
photograph taken.

Here's a sample of shots I took at GoGaRuCo 2013. Tons more photos are linked
here: [[http://www.railsonmaui.com/blog/2013/09/22/gogaruco-2013/][GoGaRuCo 2013: Community > Code]].

{% img /images/2014-08-13-2014-golden-gate-ruby-conference/gogaruco-2013-1.jpg %}

{% img /images/2014-08-13-2014-golden-gate-ruby-conference/gogaruco-2013-2.jpg %}

{% img /images/2014-08-13-2014-golden-gate-ruby-conference/gogaruco-2013-3.jpg %}

{% img /images/2014-08-13-2014-golden-gate-ruby-conference/gogaruco-2013-4.jpg %}

{% img /images/2014-08-13-2014-golden-gate-ruby-conference/gogaruco-2013-5.jpg %}

* Available for Consulting
If you'd like to meet me around the time of GoGaRuCo, don't hesitate to email me
to try to meet up in person. Possibly you might have a project that could use my
help?

On a personal note, I spent the better part of my adulthood in San Francisco, so
I've got tons of friends there. All my consulting clients tend to be from the
Bay Area as well.

