#+BEGIN_HTML
---
layout: post
title: "RailsConf 2014"
date: 2014-04-23 08:02:41 -0500
comments: true
categories: 
keywords: 
description: RailsConf Notes
---
#+END_HTML

* My Talk: Concerns, Decorators, Presenters, Service Objects, Helpers, Help me Decide
- [[https://www.icloud.com/iw/#keynote/BALu9Dy-Dcbu1PvWluyB_G-jq5C6URGmij2F/RailsConf-2014-Concerns-Decorators-Presenters-Service-Objects-Helpers-Help-Me-Decide-April-22-2014][Slides]]
- [[https://github.com/justin808/fat-code-refactoring-techniques][Fat Code Refactoring Techniques on Github]]


* (Lack of) Live Coding in my Talk
Due to time constraints, I chose to skip the live coding I had prepared to do in
my talk. [[emailto:justin@railsonmaui.com][Please let me know]] if you'd be interested in a screencast walking
through the sample code. I will create one if there is sufficient demand.

*If you really wanted to see me doing live coding, you're in luck!* I'm
available all day today and tomorrow to do nothing but go over the code samples
I created in RubyMine using the Vim plugin. I'll be at the RubyMine booth all
day on Wednesday and Thursday, aside from being at the AirPair booth from
11:00am to 11:30am on Wednesday, April 23, 2014.

{% img /images/2014-04-23-RailsConf/railsconf-fat-models-book-title.JPG %}

* Pictures
Please tag yourself and your friends. If you want me to grab a picture for you,
please let me know!

- [[https://www.facebook.com/media/set/?set%3Da.788587014486399.1073741836.484394724905631&type%3D3][Day 0, speaker dinner]] 
- [[https://www.facebook.com/media/set/?set%3Da.788590134486087.1073741837.484394724905631&type%3D3&uploaded%3D52][Day 1, including after parter at the Public House]]

#+begin_html
<div id="fb-root"></div> <script>(function(d, s, id) { var js, fjs = d.getElementsByTagName(s)[0]; if (d.getElementById(id)) return; js = d.createElement(s); js.id = id; js.src = "//connect.facebook.net/en_US/all.js#xfbml=1"; fjs.parentNode.insertBefore(js, fjs); }(document, 'script', 'facebook-jssdk'));</script>
<div class="fb-post" data-href="https://www.facebook.com/photo.php?fbid=788587434486357&amp;set=a.788587014486399.1073741836.484394724905631&amp;type=1" data-width="466"><div class="fb-xfbml-parse-ignore"><a href="https://www.facebook.com/photo.php?fbid=788587434486357&amp;set=a.788587014486399.1073741836.484394724905631&amp;type=1">Post</a> by <a href="https://www.facebook.com/railsonmaui">Rails On Maui</a>.</div></div>
#+end_html

#+begin_html
<div id="fb-root"></div> <script>(function(d, s, id) { var js, fjs = d.getElementsByTagName(s)[0]; if (d.getElementById(id)) return; js = d.createElement(s); js.id = id; js.src = "//connect.facebook.net/en_US/all.js#xfbml=1"; fjs.parentNode.insertBefore(js, fjs); }(document, 'script', 'facebook-jssdk'));</script>
<div class="fb-post" data-href="https://www.facebook.com/photo.php?fbid=788591081152659&amp;set=a.788590134486087.1073741837.484394724905631&amp;type=1" data-width="466"><div class="fb-xfbml-parse-ignore"><a href="https://www.facebook.com/photo.php?fbid=788591081152659&amp;set=a.788590134486087.1073741837.484394724905631&amp;type=1">Post</a> by <a href="https://www.facebook.com/railsonmaui">Rails On Maui</a>.</div></div>
#+end_html

I hope you like the pictures.
