#+BEGIN_HTML
---
layout: page
title: "RubyMine Tips"
sharing: true
footer: true
date: 2014-03-07 17:57
comments: true
# categories: [RubyMine, Vim]
keywords: RubyMine, RailsTutorial.org, Tips, Productivity, Rails, IdeaVim
published: true
description: Landing page for rubymine tips.
---
#+END_HTML

* [[file:why-rubymine.html][Why RubyMine?]]
Why do I use RubyMine?

* [[file:rubymine-tips-rails-tutorial.html][Favorite RubyMine Tips]]
Screencast and list of my favorite RubyMine tips.
* [[http://www.railsonmaui.com/blog/2014/05/06/remote-pair-programming-tips-using-screenhero/][Remote Pair Programming Tips using RubyMine and Screenhero]]
RubyMine works great for Remote Pairing!  

* Short Tips 
** [[http://www.railsonmaui.com/blog/2014/01/25/using-rubymine-slash-intellij-regexp-search-slash-replace/][Using RubyMine/IntelliJ Regexp Search/Replace]]
RubyMine’s interactive search/replace is awesome. The Regexp feature is
especially useful. Not only will it help you edit faster, but it will improve
your ability to write RegExp’s in your code. When do you need to use a regexp?
Whenever a standard find/replace won’t cut it.
