#+BEGIN_HTML
---
layout: page
title: "About Justin Gordon"
date: 2013-08-15 18:03
comments: false
sharing: true
footer: true
keywords: Rails, Justin Gordon, Consulting, Ruby on Rails, Maui
description: About the Rails on Maui website and Justin Gordon's background.
---
#+END_HTML
I have been passionately writing software since 1985, focusing on Java since
1996 at several startups and with Ruby on Rails since 2011. 

My consulting practice has grown. Here's the story: [[http://www.shakacode.com/2015/09/17/who-is-shaka-code.html][Who is ShakaCode?]]

Please contact me at [[mailto:justin@shakacode.com][justin@shakacode.com]] if you're interested in Rails
consulting. This blog is created using Octopress, as described [[file:../blog/2013/04/27/octopress-setup-with-github-and-org-mode/index.html][here]].

#+begin_quote
"Would you bet on a NASCAR driver who can't drive stick? No? Then fire every
developer who doesn't use Vim or Emacs.", the "Hipster Hacker" on Twitter.
#+end_quote

* Links to Details
+ I +like+ love to program. Here's a narrative of [[file:about-justin-gordon-programming.html][Justin's years tinkering with computers]].
+ [[file:justin-gordon-resume.html][My resume]].
+ I telecommute from Maui. [[file:telecommuting.html][Why telecommuting works and how I maximize productivity]].

{% img /about/Justin-Office-2013.JPG %}

* Some Bullets
+ Rails projects: http://www.blinkinc.com and a several other startups.
+ I use ideaVim inside of RubyMine and IntelliJ and Evil (vim) mode inside of
  emacs. And almost everything I do is backed by developer written tests.
  Recently, I switched to [[https://github.com/syl20bnr/spacemacs][Spacemacs]].
+ Experienced and passionate software engineer with a track record of successful projects.
+ Responsible for majority of design and coding of the core storage layer behind
  the [[http://public.dhe.ibm.com/common/ssi/ecm/en/iml14344usen/IML14344USEN.PDF][Gartner 2012]] leading program for product master data management:
  [[http://www-01.ibm.com/software/data/infosphere/mdm/collaborative.html][InfoSphere MDM Collaborative Edition]]. This involved tons of TDD along with
  tons of experience optimizing Java code in Yourkit, and inventing clever time
  and space solutions, including binary data stores and distributed caching.
+ Love programming in Ruby on Rails and the whole wonderful ecosystem of Heroku,
  Amazon EC2, jQuery, coffeescript, haml, sass, etc.
+ Close connections to the Jetbrains team and expert with their tools: IntelliJ and RubyMine.
+ Love writing tests in rspec, and phantomjs with capybara is simply amazing.
  Finally, developers can write tests on the full stack, including all client
  side javascript.
+ Twitter Bootstrap rocks.
+ Previously specialized in Master Data Manager for Product Information Management.
+ Thought leader in doing Test Driven Development in the context of enterprise
  software.
+ Author of open source project "Dependent Object Framework", which vastly
  simplifies and accelerates JUnit testing with persistent dependencies.
+ Former speaker at Dr. Dobb's SD West Santa Clara, Architecture and Design
  World Chicago, and SD Best Practices in Boston. Talks were on "JUnit and
  Test-Driven Development: Why and How in Enterprise Software" and the
  "Dependent Object Framework for Enterprise TDD".
+ Tons I didn't mention, but stuff you'd expect given my experience. Here's a
  few more things I like using: postgres, tmux, yaml, json, rubygems (too many
  to list), and the Canary's webkit debugger.
+ Graduated in 1991 with an AB magna cum laude in applied mathematics from
  Harvard and received an MBA from UC Berkeley in 2001.

* Outside of Programming
Besides writing great software, Justin enjoys the ocean sports found in Maui,
and has done quite a bit of home improvement, having designed and built the
Sugar Ranch, a B&B (pending application) where he lives with his family. You can
read more about Sugar Ranch here http://www.sugarranchmaui.com and here:
http://www.facebook.com/sugarranch.


[[https://maps.google.com/maps?q%3D141%2BMakahiki%2BSt,%2BPaia,%2BHI&hl%3Den&ll%3D20.908851,-156.408621&spn%3D0.002944,0.003433&sll%3D20.46,-157.505&sspn%3D12.075058,9.876709&oq%3D141&t%3Dw&hnear%3D141%2BMakahiki%2BSt,%2BPaia,%2BMaui,%2BHawaii%2B96779&z%3D19&iwloc%3Dr0&source%3Dgplus-ogsb][Map of Sugar Ranch]].

As you drive up to Sugar Ranch...
{% img /about/SugarRanchFrontEvening.jpg %}

The back side of Sugar Ranch...
{% img /about/SugarRanchRearEvening.jpg %}
