#+BEGIN_HTML
---
layout: page
title: "Justin Gordon Resume"
date: 2013-05-06 22:04
comments: true
sharing: true
footer: true
---
#+END_HTML
Contact: at gmail, =justin.gordon=, 141 Makahiki Street, Paia, HI 96779, (808)
281-7272 (M), [[https://www.linkedin.com/in/railsonmaui][Linked In]].

* Overview
+ Currently Rails consulting.
+ From the backend persistence layer to the Ruby layer, to client side
  JavaScript, I've got projects covered. I'm typically adding code to Github
  and submitting a pull request within a day of joining a project.
+ Ruby on Rails full stack engineer, ruby, coffeescript, jQuery, saas, haml.
+ Extensive contributions to high performance Java enterprise applications used
  by the world's largest retailers.
+ Areas of expertise include: Ruby on Rails, Test Driven Development ([[http://rspec.info/][rspec]] and
  [[http://junit.org/][JUnit]]), profiling and optimizing (with [[http://www.yourkit.com/][Yourkit]]), concurrency, caching, EmberJs.

* Education
+ *University of California at Berkeley*, Walter Haas School of Business MBA, December 2001, Beta Gamma Sigma, Management of Technology Certificate
+ *Harvard University*, BA Applied Mathematics, Magna Cum Laude, 1991
+ *Chartered Financial Analyst*, 1996

* Experience
** Rails Consulting Projects
+ Rails projects with significant contributions: http://www.housinglist.com and
  http://www.blinkinc.com.
+ Please email me at =justin.gordon= at =gmail.com= or if you're interested in
  learning how I might be able to help your business.

** IBM (Trigo Acquisition), [[http://www-01.ibm.com/software/data/infosphere/mdm/collaborative.html][InfoSphere MDM Collaborative Edition]]
+ [[http://www.railsonmaui.com/about/about-justin-gordon-programming.html#sec-3][Narrative of Details]]
+ November, 2002 to 2013. Team Lead, Senior Engineer, Architect, in
  Burlingame, CA and telecommuting from Maui since 2007.
+ The world's largest retailers, including Walmart and Lowes, use the algorithms
  designed, implemented, and optimized by Justin to store and edit all their vendor
  product data *currently*.
+ Java software engineering leadership on 3 tier web-based enterprise
  application for product information management, collection and distribution,
  for the world’s largest retailers.
+ Broad contributions to all aspects of the leading ([[http://public.dhe.ibm.com/common/ssi/ecm/en/iml14344usen/IML14344USEN.PDF][according to Gartner]])
  product for Master Data Management of Product Information, used by many of
  the world's largest retailers.
+ Most significant contribution is the lead implementer of improved storage
  layer architecture from shredded database tables to highly performing
  binary serialization, using an XP development methodology (TDD, pair programming,
  and scrum meetings), along with a mechanism of searching the data via database
  XML.
+ Responsible for the majority of server side performance optimizations, such as
  the use of EhCache distributed caching. Led integration of profilers into PIM
  product for more efficient customer support.
+ Responsible for all development aspects of releases from 4.2.1, 5.0.1 (Home
  Depot/Albertsons “Large Retailer” release), 6.x, and 9.x, from negotiation of
  product feature set and schedule, to developer assignments, to handling
  resource re-allocations, to development procedures, to bug triage, and final
  release.
+ Process and innovation driver: Instigated move toward Agile Development
  Methodologies, including Pair Programming and Test Driven Development (TDD).
+ Main contact for tough customer issues, especially regarding performance (cpu
  and memory usage), data integrity, caching, and threading issues.
+ Developed methodology to bring TDD product wide using the Dependent Object
  Framework.

** Extensity
+ 1999-2001, Emeryville, CA, Architect, Tools
+ Responsible for all of Extensity’s development efforts (all Java) aimed at
  system administrators and integrators, including serving as the co-architect
  of cross-functional efforts to improve the efficiency of Extensity’s
  professional services. Conducted architecture and code reviews, gathered
  customer requirements, created design documents, conducted training sessions,
  and supervised team members. Awarded "Employee of the Month" for October 2000.
  Promoted from “Team Lead” to “Architect” in June 2000.
+ Led re-architecture of 5.0 System Administration Tool, from marketing
  requirements and initial design plans to coding and refinement to GA in
  June 2000.
+ Primary designer and implementer of “Group Based Data” (Application security)
+ Architect of the GuiEditor, an internal tool for designing screens and other
  installation customizations. Designed and coded tools for configuration of
  sample and meta data.
+ Led the design for multinational organizations with features such as support for VAT.

** Other Experience
In the 1990's, I did C++/Sybase investment programming at [[http://www.mcm.com/][Mellon Capital]] and
Java programming for a startup Infoscape. Here's some details from an [[file:justin-gordon-resume-1990s.html][older
resume]] if you're interested.

  
* Patents
+ [[http://appft1.uspto.gov/netacgi/nph-Parser?Sect1%3DPTO1&Sect2%3DHITOFF&d%3DPG01&p%3D1&u%3D/netahtml/PTO/srchnum.html&r%3D1&f%3DG&l%3D50&s1%3D%252220070244865%2522.PGNR.][Method and system for data retrieval using a product information search engine]]
+ [[http://appft1.uspto.gov/netacgi/nph-Parser?Sect1%3DPTO1&Sect2%3DHITOFF&d%3DPG01&p%3D1&u%3D/netahtml/PTO/srchnum.html&r%3D1&f%3DG&l%3D50&s1%3D%252220090210434%2522.PGNR.][STORAGE AND RETRIEVAL OF VARIABLE DATA]]
+ [[http://appft1.uspto.gov/netacgi/nph-Parser?Sect1%3DPTO1&Sect2%3DHITOFF&d%3DPG01&p%3D1&u%3D/netahtml/PTO/srchnum.html&r%3D1&f%3DG&l%3D50&s1%3D%252220090178029%2522.PGNR.][Dependent Object Framework for JUnit Testing]]. 

* Publications
+ My talks at Dr. Dobbs were the basis for the chapter on Test Driven
  Development in [[http://www.distributedscrum.com/?page_id%3D11][A Practical Guide to Distributed Scrum]].

