#+BEGIN_HTML
---
layout: page
title: "Telecommuting From Maui"
date: 2013-05-06 22:09
comments: true
sharing: true
footer: true
keywords: telecommuting, Maui, productivity, hire, rework, Remote Office
description:  Why hire a remote worker and achieving maximum productivity in a remote office.
---
#+END_HTML
I've been working remotely from Maui full time since 2007. My home office is
optimized for productivity.
#+begin_html
{% img /about/Productive-Office-2012-940.jpg 940 623 %}
#+end_html

* Some Famous Authors on Telecommuting
Jeff Attwood (who started Stack Overflow) has a great article on this topic, [[http://www.codinghorror.com/blog/2010/05/on-working-remotely.html][On
Working Remotely]]:
#+begin_quote
The reason remote development worked for us, in retrospect, wasn't just shared
love of code. I picked developers who I knew -- I had incontrovertible proof --
were amazing programmers. I'm not saying they're perfect, far from it, merely
that they were top programmers by any metric you'd care to measure. That's why
they were able to work remotely. Newbie programmers, or competent programmers
who are phoning it in, are absolutely not going to have the moxie necessary to
get things done remotely -- at least, not without a pointy haired manager, or
grumpy old team lead, breathing down their neck. Don't even think about working
remotely with anyone who doesn't freakin' bleed ones and zeros, and has a proven
track record of getting things done.
#+end_quote

Jason Freid and David Heinemeier Hansson (aka DHH) have an upcoming book on the topic: [[http://www.amazon.com/Remote-Office-Required-Jason-Fried/dp/0804137501][Remote:
Office Not Required]]. These are the guys that wrote [[http://www.amazon.com/Rework-Jason-Fried/dp/0307463745/ref%3Dpd_sim_b_1][Rework]]. Here's a quote from
that book:
#+begin_quote
It's crazy not to hire the best people just because they live far away.
Especially now that there's so much technology out there making it easier to
bring everyone together online.

Also, meet in person once in a while. You should see each other at least every
few months. We make sure our whole team gets together a few times a year. These
are great times to review progress, discuss what's going right or wrong, plan
for the future, and get reacquainted with one another on a personal level.
#+end_quote

The Ruby Rogues recently commented on telecommuting on episode: [[http://rubyrogues.com/108-rr-ruby-trends/][108 RR Ruby
Trends]], at 33:26, or scroll down for the transcript. Here's a snippet, although
I prefer listening to the podcast (at 1.5x speed on my iPhone).
#+begin_quote
KATRINA: Thoughtbot also had a no-remote-work policy. And then, they lost too
many people. And then, when one of their other best guys was going to move to
Sweden, I think, he was like, “Okay. I’m quitting because I’m moving to Sweden.”
And they were like, “Maybe we should rethink this.” [Chuckles]
#+end_quote


* Productivity Features of My Home Office
+ *FAST Internet*. I've got 35/7 cable plus 7/1 DSL on a
  [[http://www.amazon.com/gp/product/B0042WCFI2/ref%3Das_li_ss_tl?ie%3DUTF8&camp%3D1789&creative%3D390957&creativeASIN%3DB0042WCFI2&linkCode%3Das2&tag%3Draionmau-20][ZyXEL load balancing router]] on a UPS. Even if the power goes out, it's likely I can
  still work at nearly 100% with the network still running. And one person's
  upload of a movie to youtube has no perceptible affect on the network.
  Previously, with only DSL, one person's upload of a movie would bring the
  network to a crawl.
+ *FAST computers* with many large monitors
+ *A/C*, not only to control the temperature (which can be important in Hawaii),
  but also to block out any noise, such as when the gardeners come to mow.
+ A nice *sound system*. Depending on my mood, I may prefer listening to Mozart,
  Moby, or the Rolling Stones on [[http://www.pandora.com/][Pandora]] when coding.
+ *Ergonomics*: [[http://www.humanscale.com/products/product_detail.cfm?group%3DKeyboardSystems][keyboard tray]], [[http://www.amazon.com/Kinesis-KB500USB-BLK-Advantage-Contoured-Keyboard/dp/B000LVJ9W8/ref%3Dsr_1_1?s%3Delectronics&ie%3DUTF8&qid%3D1367693935&sr%3D1-1&keywords%3Dkinesis%2Badvantage][Kinesis keyboard]], really good chair, wireless mouse
+ *Microphone*, pro-quality: [[http://www.amazon.com/gp/product/B002VA464S/ref%3Das_li_ss_tl?ie%3DUTF8&camp%3D1789&creative%3D390957&creativeASIN%3DB002VA464S&linkCode%3Das2&tag%3Draionmau-20][Blue Yeti]].
+ Multiple phone lines
+ *Caffeine*: [[http://www.amazon.com/gp/product/B005IOME0W/ref%3Das_li_ss_tl?ie%3DUTF8&camp%3D1789&creative%3D390957&creativeASIN%3DB005IOME0W&linkCode%3Das2&tag%3Draionmau-20][Nespresso]] coffee maker and [[http://www.amazon.com/gp/product/B003LNOPSG/ref%3Das_li_ss_tl?ie%3DUTF8&camp%3D1789&creative%3D390957&creativeASIN%3DB003LNOPSG&linkCode%3Das2&tag%3Draionmau-20][Breville Tea Maker]]. I use both of these every
  single day. The tea maker can you into a tea lover of green tea, even if you
  didn't care much for bagged green tea.

* Tips
+ I've got a sign on my door that really seems to cut down on disturbances from
  the family. That's critical to getting into a state of "flow".
  #+begin_html
  {% img /about/do-not-break-my-flow-940.jpg 940 336 %}
  #+end_html
+ When teleconferencing using the Yeti Mic, it's best to use the only a speaker
  from the computer or monitor that is behind the mic. If you have speakers
  around your office, and you use those, then you'll get an echo effect on the
  microphone, which can be configured to only take sound from the front.

If you've got any tips I missed, let me know!


#+OPTIONS: toc:0   
